networks:
  rpg_network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:

services:
  # Traefik - Reverse Proxy
  traefik:
    image: traefik:v2.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    networks:
      - rpg_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.local`)"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  # Backend (Rust API)
  backend:
    build: ./backend
    container_name: rpg-backend
    environment:
      - DATABASE_URL=postgres://user:password@db/rpg
    networks:
      - rpg_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.local`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  # Frontend (React, Vue, etc.)
  frontend:
    build: ./frontend
    container_name: rpg-frontend
    networks:
      - rpg_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.local`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  # Database (PostgreSQL)
  db:
    image: postgres:13
    container_name: rpg-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rpg
    networks:
      - rpg_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Jenkins CI/CD
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - rpg_network
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.local`)"

  # Keycloak for Authentication
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=rpg
      - DB_USER=user
      - DB_PASSWORD=password
    networks:
      - rpg_network
    ports:
      - "8082:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.local`)"

  # Grafana for monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - rpg_network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - rpg_network
    ports:
      - "9090:9090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)"

  # Add any additional services here (e.g., cache, queue, etc.)

networks:
  rpg_network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
  jenkins_home:
